#ifndef MGPROTO_CPP
#define MGPROTO_CPP


#include "MGProto.hpp"


const char* info_game_messages[] =
{
				"*INFO_MESSAGE|AUCTION_RESULTS",
				"*INFO_MESSAGE|SUCCESS_CHARGES_PAY",
				"*INFO_MESSAGE|PLAYER_BANKROT",
				"*INFO_MESSAGE|LOST_ALIVE_PLAYER",
				"*INFO_MESSAGE|PRODUCED",
				"*INFO_MESSAGE|STARTINSECONDS",
				"*INFO_MESSAGE|GAME_STARTED",
				"*INFO_MESSAGE|STARTING_GAME_INFORMATION",
				"*INFO_MESSAGE|STARTCANCELLED",
				"*INFO_MESSAGE|PAY_FACTORY_SUCCESS",
				"*INFO_MESSAGE|FACTORY_BUILT",
				"*INFO_MESSAGE|VICTORY_MESSAGE",
				"*INFO_MESSAGE|GAME_ALREADY_STARTED",
				"*INFO_MESSAGE|SERVER_FULL",
				"*INFO_MESSAGE|NEW_PLAYER_CONNECT",
				"*INFO_MESSAGE|GAME_NOT_STARTED",
				"*INFO_MESSAGE|LOST_LOBBY_PLAYER",
				"*INFO_MESSAGE|NEW_TURN",
				"*INFO_MESSAGE|WAIT_FOR_NEXT_TURN",
				"*INFO_MESSAGE|UNKNOWN_COMMAND",
				"*INFO_MESSAGE|HELP_COMMAND_SUCCESS",
				"*INFO_MESSAGE|MARKET_COMMAND_SUCCESS",
				"*INFO_MESSAGE|PLAYER_COMMAND_NOT_FOUND",
				"*INFO_MESSAGE|PLAYER_COMMAND_SUCCESS",
				"*INFO_MESSAGE|PLAYER_COMMAND_INCORRECT_ID",
				"*INFO_MESSAGE|LIST_COMMAND_SUCCESS",
				"*INFO_MESSAGE|PROD_COMMAND_SUCCESS",
				"*INFO_MESSAGE|PROD_COMMAND_NO_FACTORIES",
				"*INFO_MESSAGE|PROD_COMMAND_NO_MONEY",
				"*INFO_MESSAGE|PROD_COMMAND_NO_SOURCE",
				"*INFO_MESSAGE|BUILDING_FACTORIES_LIST",
				"*INFO_MESSAGE|BUILDING_FACTORIES_LIST_EMPTY",
				"*INFO_MESSAGE|BUILD_COMMAND_INCORRECT_ARG",
				"*INFO_MESSAGE|BUILD_COMMAND_SUCCESS",
				"*INFO_MESSAGE|BUILD_COMMAND_NO_MONEY",
				"*INFO_MESSAGE|BUY_COMMAND_ALREADY_SENT",
				"*INFO_MESSAGE|BUY_COMMAND_NO_MONEY",
				"*INFO_MESSAGE|BUY_COMMAND_SUCCESS",
				"*INFO_MESSAGE|BUY_COMMAND_INCORRECT_PRICE",
				"*INFO_MESSAGE|BUY_COMMAND_INCORRECT_AMOUNT",
				"*INFO_MESSAGE|SELL_COMMAND_ALREADY_SENT",
				"*INFO_MESSAGE|SELL_COMMAND_SUCCESS",
				"*INFO_MESSAGE|SELL_COMMAND_INCORRECT_PRICE",
				"*INFO_MESSAGE|SELL_COMMAND_INCORRECT_AMOUNT",
				"*INFO_MESSAGE|TURN_COMMAND_SUCCESS",
				"*INFO_MESSAGE|QUIT_COMMAND_SUCCESS",
				nullptr
};

const char* error_game_messages[] =
{
				"*ERROR_MESSAGE|INTERNAL_SERVER_ERROR",
				nullptr
};

#endif
