#ifndef MGPROTO_HPP
#define MGPROTO_HPP


enum
{
					AUCTION_RESULTS,
					SUCCESS_CHARGES_PAY,
					PLAYER_BANKROT,
					LOST_ALIVE_PLAYER,
					PRODUCED,
					STARTINSECONDS,
					GAME_STARTED,
					STARTING_GAME_INFORMATION,
					STARTCANCELLED,
					PAY_FACTORY_SUCCESS,
					FACTORY_BUILT,
					VICTORY_MESSAGE,
					GAME_ALREADY_STARTED,
					SERVER_FULL,
					NEW_PLAYER_CONNECT,
					GAME_NOT_STARTED,
					LOST_LOBBY_PLAYER,
					NEW_TURN,
					WAIT_FOR_NEXT_TURN,
					UNKNOWN_COMMAND,
					HELP_COMMAND_SUCCESS,
					MARKET_COMMAND_SUCCESS,
					PLAYER_COMMAND_NOT_FOUND,
					PLAYER_COMMAND_SUCCESS,
					PLAYER_COMMAND_INCORRECT_ID,
					LIST_COMMAND_SUCCESS,
					PROD_COMMAND_SUCCESS,
					PROD_COMMAND_NO_FACTORIES,
					PROD_COMMAND_NO_MONEY,
					PROD_COMMAND_NO_SOURCE,
					BUILDING_FACTORIES_LIST,
					BUILDING_FACTORIES_LIST_EMPTY,
					BUILD_COMMAND_INCORRECT_ARG,
					BUILD_COMMAND_SUCCESS,
					BUILD_COMMAND_NO_MONEY,
					BUY_COMMAND_ALREADY_SENT,
					BUY_COMMAND_NO_MONEY,
					BUY_COMMAND_SUCCESS,
					BUY_COMMAND_INCORRECT_PRICE,
					BUY_COMMAND_INCORRECT_AMOUNT,
					SELL_COMMAND_ALREADY_SENT,
					SELL_COMMAND_SUCCESS,
					SELL_COMMAND_INCORRECT_PRICE,
					SELL_COMMAND_INCORRECT_AMOUNT,
					TURN_COMMAND_SUCCESS,
					QUIT_COMMAND_SUCCESS
};

enum
{
					INTERNAL_SERVER_ERROR
};


extern const char* info_game_messages[];
extern const char* error_game_messages[];

#endif
